gamepad_teleop:
  ros__parameters:
    steering_axis: 0
    lt_axis: 2
    rt_axis: 5
    deadman_button: 4

    max_linear_speed: 0.3
    max_angular_speed: 1.0

    throttle_deadzone: 0.05
    joy_timeout: 0.5